### ISSUE TITLE
generate_base_ccy_prices produces wrong prices

### ISSUE THREAD

**Issue by akotulski** [tarioch/beancounttools#6]
Thank you for this plugin, I was looking for something like this for quite some time (didn't think it was this easy to implement)

After switching the plugin on, my balance sheet didn't look right to me:
Input:
```
plugin "tariochbctools.plugins.generate_base_ccy_prices" "CCC"

2020-01-01 price X 100 USD
2020-01-01 price USD 2 CCC
```
it should produce
```
2020-01-01 price X 200 CCC <-- (not 50 CCC)
```
It's working after replacing division with multiplication:
https://github.com/tarioch/beancounttools/blob/master/src/tariochbctools/plugins/generate_base_ccy_prices.py#L14

**Comment by tarioch** [comment]
Thanks a lot, fixed it and created a new release for it. I somehow never noticed it, mostly because the ccy I'm using are almost 1:1.
