### ISSUE TITLE
Nordigen EUA expiration

### ISSUE THREAD

**Issue by jbrok** [tarioch/beancounttools#65]
Hello, I'm using the Nordigen API from this package to download all transactions from my 'long tail' or non-main spending accounts (Revolut, etc.). Thanks so much for open sourcing this. However, occasionally I get the following message:

> EUA was valid for 90 days and it expired at 2022-02-11 18:12:34.959764. The end user must connect the account once more with new EUA and Requisition","status_code":400}

What is the best way to generate a new EUA without having to link the accounts again which creates also a new UUID..

**Comment by tarioch** [comment]
Unfortunately I haven't found a way to renew it.

But I think the account id actually was stable when I recreated the account the last time. And worst case you'll have to update it in the config, but the beancount account you're mapping it to, will stay the same.

**Comment by jbrok** [comment]
Yes, l'm using those! Helps a lot so I think I'll just create a small note so I can easily copy/paste the code every now and then. Thanks!
