### ISSUE TITLE
Integrate into jbms/beancount-import

### ISSUE THREAD

**Issue by kosli** [tarioch/beancounttools#75]
It would be great to see these importers (and even some that were added in the forks like https://github.com/tarioch/beancounttools/compare/master...c-vigo:beancounttools:master) integrated/merged into https://github.com/jbms/beancount-import

**Comment by tarioch** [comment]
I think it makes more sense to keep those separated, I see that beancount-import is capable to use standard beancount importers. 

As long as the importers stick to standard beancount importers they can be used by the different tools such as pure beancount, fava, beancount-importer and others.

**Comment by kosli** [comment]
Thanks @tarioch
Good point to use it separately with beancount-importer, whereas I am currently struggling to use e.g. the Revolut Importer with beancount-importer. I assume you haven't used yourself the beancount-importer yet? :-)

**Comment by tarioch** [comment]
No, my setup is fava and smartimporter, which works perfectly for me.
