### ISSUE TITLE
Nordigen importer crashes

### ISSUE THREAD

**Issue by redfast00** [tarioch/beancounttools#93]
(redacted) part of the crash log:

```
File "/home/user/venv/lib/python3.10/site-packages/tariochbctools/importers/nordigen/importer.py", line 75, in extract
    " ".join(trx["remittanceInformationUnstructuredArray"]),
KeyError: 'remittanceInformationUnstructuredArray'
```

When I go to the developer view over at the Nordigen website and look at my transactions, I see that the JSON dicts contain a `remittanceInformationUnstructured` key, but not the expected `remittanceInformationUnstructuredArray` key. This matches the API docs (https://ob.nordigen.com/api/docs#/accounts/retrieve%20account%20transactions%20v2_2). Perhaps the API got updated?

**Comment by tarioch** [comment]
Actually I see this 
![image](https://user-images.githubusercontent.com/2998148/236160653-2029bde2-cb66-4648-be8f-13f62250d2db.png)

But it's optional, probably in my case it's present and in yours it isn't I'll adjust the code to not fail if it's not present and then create a new release, I'll let you know once this is done, then you can test and let me know if it works for you.

**Comment by tarioch** [comment]
Just released it, please let me know if that works for you.
