### ISSUE TITLE
Nordigen importer: include debtorName/creditorName

### ISSUE THREAD

**Issue by redfast00** [tarioch/beancounttools#95]
In the Nordigen API, there's a debtorName/creditorName field (depending on if it's an incoming or outgoing transaction). This data is very useful for labeling transactiosn/setting the incoming and outgoing account when importing transactions; it would be nice if this were included in the import.

**Comment by tarioch** [comment]
added them to the metadata, let me know if you need anything else

**Comment by redfast00** [comment]
Thank you :D
